//Hung Anh Ho
//2-21-2023
//Description: Chapter 2 - SalesPrediction

#include<iostream>;
using namespace std;

int main()
{
	//Input
	double annualSales = 8.6;
	int percentSales = 58;

	//Process
	double generatedSales = annualSales * (percentSales / 100.0);
	cout << "Sales generated by the East Coast division this year: $" << generatedSales << " (millions)\n";

	//Output
	return 0;
}